# Patches CVE-2026-68770: a critical arbitrary-code-execution bug in
# sentence-transformers <=5.5.1 that triggers on local model load even
# with trust_remote_code=False. Upgrading is required regardless of
# which embedding model you use.
FROM ghcr.io/open-webui/open-webui:v0.11.4@sha256:9591b13f13843c7721c2b8eaf7382846c81b3ffe126526d1888d1fed50c6a33f

RUN pip install --no-cache-dir --upgrade "sentence-transformers>5.5.1"
