[passwords]
glances=`echo $GLANCES_PASS`

[fs]
# Hide container bind mounts
hide=/etc/glances,/etc/hostname,/etc/hosts,/etc/resolv.conf

[network]
# Hide local loopback, docker bridge, veth pairs, and custom docker networks
hide=lo,docker0,veth.*,br-.*

[diskio]
# Hide snap loop devices and RAM disks
hide=loop.*,ram.*
